server:
  port: 9090
spring:
  application:
    name: web-service
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
