server:
  port: 8080

spring:
  application:
    name: zuul

zuul:
  routes:
    service.url: http://localhost:8082
  ribbon-isolation-strategy: THREAD

management:
endpoints:
  web:
    exposure:
      include: 'hystrix.stream'

ribbon.eureka.enabled: false