server:
  port: 8080

spring:
  application:
    name: zuul
  zipkin:
    baseUrl: http://127.0.0.1:9411/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0

zuul:
  routes:
    service:
      path: /service/**
      url: http://localhost:8082
  ribbon-isolation-strategy: THREAD

management:
endpoints:
  web:
    exposure:
      include: 'hystrix.stream'

ribbon.eureka.enabled: false



sample:
  zipkin:
    enabled: true